version: "3.9"
services:
  web:
    image: registry.heroku.com/codeurjc-daw-2021-22-webapp2/web
    restart: always
    depends_on:
      - db
    ports:
        - 8080:8080
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db/posts
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=dawn
        - SPRING_JPA_HIBERNATE_DDL-AUTO=update

  db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dawn
      - POSTGRES_DB=posts
    volumes:
      - ./postgres:/var/lib/postgres
