version: "3.9"
services:
  web:
    image: softweardaw/codeurjc-daw-2021-22-webapp5
        environment:
            - PORT=8443
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/softwear
            - MAILER_EMAIL=${MAILER_EMAIL}
            - MAILER_PASS=${MAILER_PASS}
        ports:
            - 8443:8443
        depends_on:
            - postgres
        restart: always

  db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dawn
      - POSTGRES_DB=posts
    volumes:
      - ./postgres:/var/lib/postgres
