version: "3.9"

services:
      
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      restart: always
      depends_on: db
      ports:
        - 8443:8443
      environment:
        - SPRING_DATASOURCE_URL=jdbc:jdbc:postgresql://localhost/posts
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=dawn
        - SPRING_JPA_HIBERNATE_DDL-AUTO=update

db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dawn
      - POSTGRES_DB=posts
    volumes:
      - ./postgres:/var/lib/postgres
